#!/bin/bash
sudo apt update && sudo apt upgrade
sudo apt install --no-install-recommends xserver-xorg-core xserver-xorg-video-intel x11-xserver-utils x11-xkb-utils x11-utils xinit\
                                         xserver-xorg-input-synaptics xserver-xorg-input-evdev xterm i3 dmenu\
                                         pulseaudio alsa-utils pavucontrol\
                                         firefox-esr

# Autologin
echo "[Service]" > override.conf
echo "ExecStart=" >> override.conf
echo "ExecStart=-/sbin/agetty --autologin $USER --noclear %I $TERM" >> override.conf
sudo rm /etc/systemd/system/getty@tty1.service.d/override.conf && sudo cp override.conf /etc/systemd/system/getty@tty1.service.d/ && rm override.conf

# Configure trackpad
sudo mkdir -p /etc/X11/xorg.conf.d
sudo rm /etc/X11/xorg.conf.d/*-synaptics.conf
sudo cp /usr/share/X11/xorg.conf.d/*-synaptics.conf /etc/X11/xorg.conf.d/
sudo sed -i 's/Identifier "touchpad catchall"/Identifier "touchpad catchall"\n        Option "TapButton1" "1"\n        Option "TapButton2" "3"\n        Option "VertScrollDelta" "-111"\n        Option "HorizScrollDelta" "-111"/g' /etc/X11/xorg.conf.d/*-synaptics.conf

# Create .xinitrc
echo "#!/bin/sh" > ~/.xinitrc
echo "exec i3" >> ~/.xinitrc

# Append startx on .bashrc
if ! grep -q startx ~/.bashrc; then echo "if [[ -z \$DISPLAY ]] && [[ \$(tty) = /dev/tty1 ]]; then startx; fi" >> ~/.bashrc; fi 
