#!/bin/bash

device="$(ip a | grep '^[0-9]: [a-z0-9]*:' | grep -o '[a-z0-9]*w[a-z0-9]*')"
echo Wireless device: $device
key="$(wpa_passphrase $1 $2 | grep -o '[^#]psk=[0-9a-z]*' | sed 's/psk=//g' )"

echo "source /etc/network/interfaces.d/*"	> interfaces
echo "auto lo"					>> interfaces
echo "iface lo inet loopback"			>> interfaces
echo "auto "$device				>> interfaces
echo "iface "$device" inet dhcp"		>> interfaces
echo "  wpa-ssid "$1				>> interfaces
echo "  wpa-psk "$key				>> interfaces

sudo rm /etc/network/interfaces && sudo cp interfaces /etc/network/ && rm interfaces

sudo /etc/init.d/networking restart
